### PR TITLE
Fix oauth process to work inside the docker

### PR DESCRIPTION
**Pull request by pacoorozco**
As you can see I've used your `preview` branch in order to make some changes:

1. Use `int128/oauth2cli` module, it's the same used by `gphotos-uploader-cli`.
1. I've made a patch to allow `oauth2cli` to listen in all interfaces. A PR int128/oauth2cli#5 has been submitted. Once it was merged, you can remove this patch an use the published release of `int128/oauth2cli`.
1. Use `gphotosuploader/gphotos-uploader-cli` repository. Added some patches to use the patched `oauth2cli` (could be removed when PR int128/oauth2cli#5 was merged & disable terminal prompt.
1. I've modified all `rootfs` to use command line arguments instead of modifying the code.

As a result, OAuth2 process could be completed and refresh token is working:

```
$ export TAG=v0.0.2
$ docker build -t gphotos:${TAG} . 
$ docker run --rm -it -p 12345:12345 -v /tmp/gconfig:/config --name gphotos gphotos:${TAG} gphotos-uploader-cli
```
Feel free to change whatever you don't like :-D

Is should close gphotosuploader/gphotos-uploader-cli#130, #8

### CODE REVIEW

**Comment by rfgamaral** [comment]
Thank you @pacoorozco, I'll see if I can find some time tomorrow to take a look.

**Comment by monkeyhat** [comment]
Hey @pacoorozco! Thanks for your efforts! Seems like @rfgamaral is busy - is there any way I can pull your branch through Docker to try it out? I'm a terrible programmer, but a willing test subject.

**Comment by pacoorozco** [comment]
Hi @monkeyhat 

You can clone my branch, build the image and run it to try it out.

```
$ git clone https://github.com/pacoorozco/docker-gphotos-uploader.git
$ cd docker-gphotos-uploader
$ git checkout fix-oauth-process
$ export TAG=v0.0.2
$ docker build -t gphotos:${TAG} . 
$ docker run --rm -it -p 12345:12345 -v /tmp/gconfig:/config --name gphotos gphotos:${TAG} gphotos-uploader-cli
```

**Comment by monkeyhat** [comment]
Thanks for your efforts @pacoorozco!  I gave this a try, but I think your changes might need to be merged with @rfgamaral's Preview branch.  

As I understand it, the Preview branch got very close to working because @rfgamaral used nip.io to solve the redirect problem (the **other** OAuth problem!) 

Setting OAuth to redirect to "localhost" doesn't work in a headless scenario - as the user is visiting the OAuth consent site from a different machine / IP to the one running the Docker container.  So when the consent site redirects back to localhost, it's not redirecting to the Docker.  With this in mind, the Preview branch requires users to specify the IP of their Docker host, and sets the redirect to [Docker host IP].nip.io.  

Of course, I might have this entirely wrong - but that's my understanding!  

Thanks again for trying, @pacoorozco!

**Comment by rfgamaral** [comment]
A new version of `oauth2cli` was released with @pacoorozco PR merged in, I'll wait until this new version finds its way into `gphotos-uploader-cli` to make the whole thing easier to integrate with my Docker image.

**Comment by rfgamaral** [comment]
I'm closing this PR because this could never be merged to the `master` branch and also not in it's current state. I've took a lot of the ideas behind @pacoorozco PR (thank you so much 🙏) and implemented them in the `preview` branch.

**Pull request closed without merging**
