### PR TITLE
Update to gphotos-uploader-cli v1.0.4

### PR DESCRIPTION
**Pull request by mshish**
Upgraded to the latest (v1.0.3). Patches were updated and the oauth2 updates patch was removed since the CLI now includes those versions. Updated `run` for v1.0.3 breaking CLI changes that requires the `push` parameter to send photos.

### CODE REVIEW

**Comment by rfgamaral** [comment]
I've been meaning to update to the latest version myself but I currently don't have the time so this is really appreciated. Thank you very much 🙇.

I've built a preview version based on your PR (pushed to DockerHub under the `preview` tag) and I've been testing the image to make sure everything is working as expected. Unfortunately there seems to be one tiny issue that we can workaround it but I'd rather have it fixed upstream.

The issue is that the `config.hjson` file is not properly initialized during a first-time setup:

```
❯ docker logs -f 26d8767806c111e249e65171426263f996ccaecf61bb9530b38e40b18c82f1e8
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 01-run-file: applying...
[fix-attrs.d] 01-run-file: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-initialize-config: executing...
[fatal]  unlinkat //config: device or resource busy
[cont-init.d] 10-initialize-config: exited 1.
[cont-init.d] 20-setup-crontab: executing...
[cont-init.d] 20-setup-crontab: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

I've done some testing and it seems that `gphotos-uploader-cli` can't initialize a config file in a root folder:

```
/ # gphotos-uploader-cli init --config=/config
[fatal]  unlinkat //config: device or resource busy
```

However, it works in a sub-folder:

```
/ # gphotos-uploader-cli init --config=/config/test
[done] √ Configuration file successfully initialized.  

Please edit:
- `/config/test/config.hjson` to add you configuration.
```

@mshish Could you please test this on your side? Either with my `preview` image or build your own on your side, shouldn't matter.

**Comment by rfgamaral** [comment]
@mshish Sorry if I wasn't clear but that latest commit is not the change I'm looking for; this probably needs to be fixed upstream. That change will also break the upgrade path for everyone.

At the very least this should be a new patch that fixes the issue in `gphotos-uploader-cli`, without changing anything on the Docker image side.

**Comment by mshish** [comment]
Thanks, realized that it would be a breaking change as I was working on it and was going to post here. I'll open an issue in the CLI project and then update this PR once upstream is fixed.

**Comment by mshish** [comment]
@rfgamaral updated with v1.0.4. Looks to be good to go.

**Review by rfgamaral — CHANGES_REQUESTED** [review]
Please update the `README.md` with:

1. Replace the block of code after `You should get an output similar to this one:` with:

```
[info]   Opening browser to complete authorization.
[warn]   Browser was not detected. Complete the authorization browsing to: http://localhost:29070
```

2. Replace the whole **fourth** item with:

```
Once the authentication process is complete you should get a green box with "Success!".
```

 3. Delete the block of code that follows the previous point, which no longer shows.

After that, it's all good :)

**Review by rfgamaral — APPROVED** [review]
Perfect 😄 Thank you again for your contribution 👌

**Comment by rfgamaral** [comment]
This has now been published to DockerHub as `1.0.4` and `latest`.

**Pull request merged**
